### PR TITLE
Stop using distutils; test against Python 3.12

### PR DESCRIPTION
**Pull request by jwodder**

### CODE REVIEW

**Comment by jwodder** [comment]
@yarikoptic Ping.

**Comment by yarikoptic** [comment]
eh, probably my resolving of conflicts online didn't go cleanly. Could you please re-do it properly @jwodder ?

**Comment by jwodder** [comment]
@yarikoptic It should be fixed now.

**Comment by yarikoptic** [comment]
Thank you!

**Comment by a-detiste** [comment]
`bts subscribe 1014890` :-)

**Pull request merged**
