### PR TITLE
RF: remove remaining usage of SIX, and thus move away fully from Python 2

### PR DESCRIPTION
**Pull request by a-detiste**
https://wiki.debian.org/Python3-six-removal

https://github.com/duecredit/duecredit/commit/523f54742b8d38ced03ad3d37ef3a061f8c6e544)

(ok i i did not read /CONTRIBUTING.md but I'm catching up...)

### Changes

- [ ] I ran tests locally and they passed
- [ ] If you would like to list yourself as a DueCredit contributor and your name is not mentioned please modify .zenodo.json file.

### CODE REVIEW

**Comment by yarikoptic** [comment]
codespell - ignore, pushed fix directly in 5b799d4a532f73146f704d4561e286487fdfee8e . But apparently we do not even run tests anymore with travis, eh... need to prep github workflow and see in general if all kosher first

**Comment by a-detiste** [comment]
pyflakes told me that `time` & `stat` where used somewhere without being defined, I included a fix for these in the PR

**Comment by yarikoptic** [comment]
I have moved testing over to github in https://github.com/duecredit/duecredit/pull/187, please rebase.

**Comment by yarikoptic** [comment]
if want to go "wilder" , might even consider using pyupgrade. E.g. see "fresh example" in https://github.com/dandi/dandi-cli/pull/1350 . It is ok IMHO to drop EOL'ed python versions while at it ;)

**Comment by yarikoptic** [comment]
thanks for the rebase!  If you get a chance and could rewrite that commit to get commit message describing the change in it (title of this PR?), not action how it came about ("rebase") -- would be appreciated!

**Comment by a-detiste** [comment]
running a plain  `pytest` fail the same here...

**Comment by yarikoptic** [comment]
<details>
<summary>odd that github didn't run any tests now here :-/ running locally there is a bunch of unrelated warnings (will address them separately) but tests pass</summary> 

```shell
❯ git describe
0.9.2-12-gca2ab95
❯ python -m pytest -s -v .
====================================================================================== test session starts =======================================================================================
platform linux -- Python 3.11.6, pytest-7.4.3, pluggy-1.3.0 -- /home/yoh/proj/duecredit/venvs/dev3.11/bin/python
cachedir: .pytest_cache
rootdir: /home/yoh/proj/duecredit
configfile: tox.ini
plugins: cov-4.1.0
collected 76 items                                                                                                                                                                               

duecredit/tests/test__main__.py::test_main_help PASSED
duecredit/tests/test__main__.py::test_main_version PASSED
duecredit/tests/test__main__.py::test_main_run_a_script PASSED
duecredit/tests/test_api.py::test_api[DueCreditCollector] PASSED
duecredit/tests/test_api.py::test_api[InactiveDueCreditCollector] PASSED
duecredit/tests/test_api.py::test_noincorrect_import_if_no_lxml PASSED
duecredit/tests/test_api.py::test_noincorrect_import_if_no_lxml_numpy[kwargs0-env0] SKIPPED (We need to have numpy to test correct operation)
duecredit/tests/test_api.py::test_noincorrect_import_if_no_lxml_numpy[kwargs0-env1] SKIPPED (We need to have numpy to test correct operation)
duecredit/tests/test_api.py::test_noincorrect_import_if_no_lxml_numpy[kwargs0-env2] SKIPPED (We need to have numpy to test correct operation)
duecredit/tests/test_api.py::test_noincorrect_import_if_no_lxml_numpy[kwargs0-env3] SKIPPED (We need to have numpy to test correct operation)
duecredit/tests/test_api.py::test_noincorrect_import_if_no_lxml_numpy[kwargs1-env0] SKIPPED (We need to have numpy to test correct operation)
duecredit/tests/test_api.py::test_noincorrect_import_if_no_lxml_numpy[kwargs1-env1] SKIPPED (We need to have numpy to test correct operation)
duecredit/tests/test_api.py::test_noincorrect_import_if_no_lxml_numpy[kwargs1-env2] SKIPPED (We need to have numpy to test correct operation)
duecredit/tests/test_api.py::test_noincorrect_import_if_no_lxml_numpy[kwargs1-env3] SKIPPED (We need to have numpy to test correct operation)
duecredit/tests/test_cmdline.py::test_import PASSED
duecredit/tests/test_cmdline.py::test_main_help PASSED
duecredit/tests/test_cmdline.py::test_main_version PASSED
duecredit/tests/test_cmdline.py::test_smoke_cmd_summary PASSED
duecredit/tests/test_cmdline.py::test_cmd_test 2023-11-10 23:04:00,996 [ERROR  ] Just use pytest duecredit for now (NotImplementedError) (main.py:179)
PASSED
duecredit/tests/test_collector.py::test_citation_paths PASSED
duecredit/tests/test_collector.py::test_entry PASSED
duecredit/tests/test_collector.py::test_dcite_method PASSED
duecredit/tests/test_collector.py::test_args_match_conditions PASSED
duecredit/tests/test_collector.py::test_dcite_match_conditions_function PASSED
duecredit/tests/test_collector.py::test_dcite_match_conditions_method PASSED
duecredit/tests/test_collector.py::test_get_output_handler_method PASSED
duecredit/tests/test_collector.py::test_collectors_uniform_api PASSED
duecredit/tests/test_collector.py::test__docs__ PASSED
duecredit/tests/test_dueswitch.py::test_dueswitch_activate PASSED
duecredit/tests/test_dueswitch.py::test_a_bad_one PASSED
duecredit/tests/test_entries.py::test_comparison PASSED
duecredit/tests/test_entries.py::test_sugaring_api PASSED
duecredit/tests/test_injections.py::TestActiveInjector::test_simple_injection[testfunc1-from duecredit.tests.mod import testfunc1-None] PASSED
duecredit/tests/test_injections.py::TestActiveInjector::test_simple_injection[TestClass1.testmeth1-from duecredit.tests.mod import TestClass1; c = TestClass1()-c.testmeth1] PASSED
duecredit/tests/test_injections.py::TestActiveInjector::test_simple_injection[TestClass12.Embed.testmeth1-from duecredit.tests.mod import TestClass12; c = TestClass12.Embed()-c.testmeth1] PASSED
duecredit/tests/test_injections.py::TestActiveInjector::test_double_injection[testfunc1-from duecredit.tests.mod import testfunc1-None] PASSED
duecredit/tests/test_injections.py::TestActiveInjector::test_double_injection[TestClass1.testmeth1-from duecredit.tests.mod import TestClass1; c = TestClass1()-c.testmeth1] PASSED
duecredit/tests/test_injections.py::TestActiveInjector::test_double_injection[TestClass12.Embed.testmeth1-from duecredit.tests.mod import TestClass12; c = TestClass12.Embed()-c.testmeth1] PASSED
duecredit/tests/test_injections.py::TestActiveInjector::test_delayed_entries SKIPPED (scipy was not found: No module named 'scipy')
duecredit/tests/test_injections.py::TestActiveInjector::test_import_mvpa2_suite SKIPPED (no mvpa2 found)
duecredit/tests/test_injections.py::TestActiveInjector::test_incorrect_path[nonexistingmodule-None] PASSED
duecredit/tests/test_injections.py::TestActiveInjector::test_incorrect_path[duecredit.tests.mod.nonexistingmodule-None] PASSED
duecredit/tests/test_injections.py::TestActiveInjector::test_incorrect_path[duecredit.tests.mod-nonexisting] 2023-11-10 23:04:01,009 [WARNING] Could not find nonexisting in module <module 'duecredit.tests.mod' from '/home/yoh/proj/duecredit/duecredit/tests/mod/__init__.py'>: module 'duecredit.tests.mod' has no attribute 'nonexisting' (injector.py:206)
PASSED
duecredit/tests/test_injections.py::TestActiveInjector::test_incorrect_path[duecredit.tests.mod-nonexisting.whocares] 2023-11-10 23:04:01,010 [WARNING] Could not find nonexisting.whocares in module <module 'duecredit.tests.mod' from '/home/yoh/proj/duecredit/duecredit/tests/mod/__init__.py'>: module 'duecredit.tests.mod' has no attribute 'nonexisting' (injector.py:206)
PASSED
duecredit/tests/test_injections.py::test_find_iobject PASSED
duecredit/tests/test_injections.py::test_no_double_activation 2023-11-10 23:04:01,010 [WARNING] Seems that we are calling duecredit_importer twice. No harm is done but shouldn't happen (injector.py:309)
PASSED
duecredit/tests/test_injections.py::test_get_modules_for_injection PASSED
duecredit/tests/test_injections.py::test_cover_our_injections PASSED
duecredit/tests/test_injections.py::test_no_harm_from_deactivate 2023-11-10 23:04:01,013 [WARNING] _orig_import is not yet known, so we haven't decorated default importer yet. Nothing TODO (injector.py:359)
PASSED
duecredit/tests/test_injections.py::test_injector_del PASSED
duecredit/tests/test_injections.py::test_injector_delayed_del PASSED
duecredit/tests/test_io.py::test_import_doi 2023-11-10 23:04:01,245 [WARNING] Failed to obtain bibtex from doi.org, retrying... (io.py:64)
2023-11-10 23:04:01,449 [WARNING] Failed to obtain bibtex from doi.org, retrying... (io.py:64)
PASSED
duecredit/tests/test_io.py::test_pickleoutput PASSED
duecredit/tests/test_io.py::test_output PASSED
duecredit/tests/test_io.py::test_output_return_all PASSED
duecredit/tests/test_io.py::test_output_tags PASSED
duecredit/tests/test_io.py::test_text_output PASSED
duecredit/tests/test_io.py::test_text_output_dump_formatting PASSED
duecredit/tests/test_io.py::test_bibtex_output PASSED
duecredit/tests/test_io.py::test_get_text_rendering PASSED
duecredit/tests/test_io.py::test_text_text_rendering PASSED
duecredit/tests/test_io.py::test_url_text_rendering PASSED
duecredit/tests/test_io.py::test_format_bibtex_zenodo_doi PASSED
duecredit/tests/test_io.py::test_format_bibtex_with_utf_characters PASSED
duecredit/tests/test_io.py::test_is_contained PASSED
duecredit/tests/test_utils.py::test_is_interactive_crippled_stdout 2023-11-10 23:04:01,501 [WARNING] Assuming non interactive session since isatty found missing (utils.py:45)
2023-11-10 23:04:01,501 [WARNING] Assuming non interactive session since isatty found missing (utils.py:45)
2023-11-10 23:04:01,501 [WARNING] Assuming non interactive session since isatty found missing (utils.py:45)
PASSED
duecredit/tests/test_versions.py::test_external_versions_basic PASSED
duecredit/tests/test_versions.py::test_external_versions_unknown PASSED
duecredit/tests/test_versions.py::test_external_versions_popular_packages[scipy] SKIPPED (could not import 'scipy': No module named 'scipy')
duecredit/tests/test_versions.py::test_external_versions_popular_packages[numpy] SKIPPED (could not import 'numpy': No module named 'numpy')
duecredit/tests/test_versions.py::test_external_versions_popular_packages[mvpa2] SKIPPED (could not import 'mvpa2': No module named 'mvpa2')
duecredit/tests/test_versions.py::test_external_versions_popular_packages[sklearn] SKIPPED (could not import 'sklearn': No module named 'sklearn')
duecredit/tests/test_versions.py::test_external_versions_popular_packages[statsmodels] SKIPPED (could not import 'statsmodels': No module named 'statsmodels')
duecredit/tests/test_versions.py::test_external_versions_popular_packages[pandas] SKIPPED (could not import 'pandas': No module named 'pandas')
duecredit/tests/test_versions.py::test_external_versions_popular_packages[matplotlib] SKIPPED (could not import 'matplotlib': No module named 'matplotlib')
duecredit/tests/test_versions.py::test_external_versions_popular_packages[psychopy] SKIPPED (could not import 'psychopy': No module named 'psychopy')

======================================================================================== warnings summary ========================================================================================
duecredit/tests/test_api.py::test_api[DueCreditCollector]
duecredit/tests/test_versions.py::test_external_versions_basic
  /home/yoh/proj/duecredit/duecredit/versions.py:80: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    return LooseVersion(version)

duecredit/tests/test_injections.py::TestActiveInjector::test_simple_injection[testfunc1-from duecredit.tests.mod import testfunc1-None]
duecredit/tests/test_injections.py::TestActiveInjector::test_simple_injection[TestClass1.testmeth1-from duecredit.tests.mod import TestClass1; c = TestClass1()-c.testmeth1]
duecredit/tests/test_injections.py::TestActiveInjector::test_simple_injection[TestClass12.Embed.testmeth1-from duecredit.tests.mod import TestClass12; c = TestClass12.Embed()-c.testmeth1]
duecredit/tests/test_versions.py::test_external_versions_basic
duecredit/tests/test_versions.py::test_external_versions_basic
duecredit/tests/test_versions.py::test_external_versions_basic
duecredit/tests/test_versions.py::test_external_versions_basic
  /home/yoh/proj/duecredit/venvs/dev3.11/lib/python3.11/site-packages/setuptools/_distutils/version.py:345: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    other = LooseVersion(other)

duecredit/tests/test_injections.py::TestActiveInjector::test_simple_injection[testfunc1-from duecredit.tests.mod import testfunc1-None]
  /home/yoh/proj/duecredit/venvs/dev3.11/lib/python3.11/site-packages/_pytest/fixtures.py:911: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  duecredit/tests/test_injections.py::TestActiveInjector::test_simple_injection[testfunc1-from duecredit.tests.mod import testfunc1-None] is using nose-specific method: `teardown(self)`
  To remove this warning, rename it to `teardown_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    next(it)

duecredit/tests/test_injections.py::TestActiveInjector::test_simple_injection[TestClass1.testmeth1-from duecredit.tests.mod import TestClass1; c = TestClass1()-c.testmeth1]
  /home/yoh/proj/duecredit/venvs/dev3.11/lib/python3.11/site-packages/_pytest/fixtures.py:911: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  duecredit/tests/test_injections.py::TestActiveInjector::test_simple_injection[TestClass1.testmeth1-from duecredit.tests.mod import TestClass1; c = TestClass1()-c.testmeth1] is using nose-specific method: `teardown(self)`
  To remove this warning, rename it to `teardown_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    next(it)

duecredit/tests/test_injections.py::TestActiveInjector::test_simple_injection[TestClass12.Embed.testmeth1-from duecredit.tests.mod import TestClass12; c = TestClass12.Embed()-c.testmeth1]
  /home/yoh/proj/duecredit/venvs/dev3.11/lib/python3.11/site-packages/_pytest/fixtures.py:911: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  duecredit/tests/test_injections.py::TestActiveInjector::test_simple_injection[TestClass12.Embed.testmeth1-from duecredit.tests.mod import TestClass12; c = TestClass12.Embed()-c.testmeth1] is using nose-specific method: `teardown(self)`
  To remove this warning, rename it to `teardown_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    next(it)

duecredit/tests/test_injections.py::TestActiveInjector::test_double_injection[testfunc1-from duecredit.tests.mod import testfunc1-None]
  /home/yoh/proj/duecredit/venvs/dev3.11/lib/python3.11/site-packages/_pytest/fixtures.py:911: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  duecredit/tests/test_injections.py::TestActiveInjector::test_double_injection[testfunc1-from duecredit.tests.mod import testfunc1-None] is using nose-specific method: `teardown(self)`
  To remove this warning, rename it to `teardown_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    next(it)

duecredit/tests/test_injections.py::TestActiveInjector::test_double_injection[TestClass1.testmeth1-from duecredit.tests.mod import TestClass1; c = TestClass1()-c.testmeth1]
  /home/yoh/proj/duecredit/venvs/dev3.11/lib/python3.11/site-packages/_pytest/fixtures.py:911: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  duecredit/tests/test_injections.py::TestActiveInjector::test_double_injection[TestClass1.testmeth1-from duecredit.tests.mod import TestClass1; c = TestClass1()-c.testmeth1] is using nose-specific method: `teardown(self)`
  To remove this warning, rename it to `teardown_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    next(it)

duecredit/tests/test_injections.py::TestActiveInjector::test_double_injection[TestClass12.Embed.testmeth1-from duecredit.tests.mod import TestClass12; c = TestClass12.Embed()-c.testmeth1]
  /home/yoh/proj/duecredit/venvs/dev3.11/lib/python3.11/site-packages/_pytest/fixtures.py:911: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  duecredit/tests/test_injections.py::TestActiveInjector::test_double_injection[TestClass12.Embed.testmeth1-from duecredit.tests.mod import TestClass12; c = TestClass12.Embed()-c.testmeth1] is using nose-specific method: `teardown(self)`
  To remove this warning, rename it to `teardown_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    next(it)

duecredit/tests/test_injections.py::TestActiveInjector::test_delayed_entries
  /home/yoh/proj/duecredit/venvs/dev3.11/lib/python3.11/site-packages/_pytest/fixtures.py:911: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  duecredit/tests/test_injections.py::TestActiveInjector::test_delayed_entries is using nose-specific method: `teardown(self)`
  To remove this warning, rename it to `teardown_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    next(it)

duecredit/tests/test_injections.py::TestActiveInjector::test_import_mvpa2_suite
  /home/yoh/proj/duecredit/venvs/dev3.11/lib/python3.11/site-packages/_pytest/fixtures.py:911: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  duecredit/tests/test_injections.py::TestActiveInjector::test_import_mvpa2_suite is using nose-specific method: `teardown(self)`
  To remove this warning, rename it to `teardown_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    next(it)

duecredit/tests/test_injections.py::TestActiveInjector::test_incorrect_path[nonexistingmodule-None]
  /home/yoh/proj/duecredit/venvs/dev3.11/lib/python3.11/site-packages/_pytest/fixtures.py:911: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  duecredit/tests/test_injections.py::TestActiveInjector::test_incorrect_path[nonexistingmodule-None] is using nose-specific method: `teardown(self)`
  To remove this warning, rename it to `teardown_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    next(it)

duecredit/tests/test_injections.py::TestActiveInjector::test_incorrect_path[duecredit.tests.mod.nonexistingmodule-None]
  /home/yoh/proj/duecredit/venvs/dev3.11/lib/python3.11/site-packages/_pytest/fixtures.py:911: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  duecredit/tests/test_injections.py::TestActiveInjector::test_incorrect_path[duecredit.tests.mod.nonexistingmodule-None] is using nose-specific method: `teardown(self)`
  To remove this warning, rename it to `teardown_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    next(it)

duecredit/tests/test_injections.py::TestActiveInjector::test_incorrect_path[duecredit.tests.mod-nonexisting]
  /home/yoh/proj/duecredit/venvs/dev3.11/lib/python3.11/site-packages/_pytest/fixtures.py:911: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  duecredit/tests/test_injections.py::TestActiveInjector::test_incorrect_path[duecredit.tests.mod-nonexisting] is using nose-specific method: `teardown(self)`
  To remove this warning, rename it to `teardown_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    next(it)

duecredit/tests/test_injections.py::TestActiveInjector::test_incorrect_path[duecredit.tests.mod-nonexisting.whocares]
  /home/yoh/proj/duecredit/venvs/dev3.11/lib/python3.11/site-packages/_pytest/fixtures.py:911: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
  duecredit/tests/test_injections.py::TestActiveInjector::test_incorrect_path[duecredit.tests.mod-nonexisting.whocares] is using nose-specific method: `teardown(self)`
  To remove this warning, rename it to `teardown_method(self)`
  See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
    next(it)

duecredit/tests/test_versions.py::test_external_versions_basic
  /home/yoh/proj/duecredit/duecredit/versions.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    return StrictVersion(version)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================================================================== slowest 10 durations ======================================================================================
0.43s call     duecredit/tests/test_io.py::test_import_doi
0.08s call     duecredit/tests/test_api.py::test_noincorrect_import_if_no_lxml
0.02s call     duecredit/tests/test_io.py::test_text_output
0.02s call     duecredit/tests/test_io.py::test_text_output_dump_formatting
0.01s call     duecredit/tests/test_injections.py::test_injector_del
0.01s call     duecredit/tests/test_injections.py::test_injector_delayed_del

(4 durations < 0.005s hidden.  Use -vv to show these durations.)
========================================================================== 58 passed, 18 skipped, 22 warnings in 0.65s ===========================================================================
 ~/proj/duecredit  no-six:master *7 ?1 ▓▒░──────────────────────────────────────────────────────────────────────────────────────────────────────────
```
</details>

**Comment by yarikoptic** [comment]
FWIW, merged https://github.com/duecredit/duecredit/pull/190 so there should be less whining from pytest happen you rebase again and we get tests running this time.  Let me also invite you to become part of the project so hopefully tests just run for your PRs.

**Comment by yarikoptic** [comment]
yeay -- it is green.  Lets release!

**Comment by a-detiste** [comment]
Sorry, sorry, sorry, I messed up my remotes in git & push to the wrong repository.

The plan was to create a PR to discuss it.

**Comment by yarikoptic** [comment]
thanks for the buzz! for it to be "clean" I just reset to the released version, so your commits are gone now  -- you are welcome now to send a PR with them.  Recommendation in general to adopt practice of feature branches -- never work directly on "master", and you will have harder time to mess up ;)

**Pull request merged**
