### PR TITLE
RF: cite-on-import -> cite-module  since we might be dealing with other languages etc

### PR DESCRIPTION
**Pull request by yarikoptic**
or might be just referencing a library/package while decorating a method,
so pretty much that citation would only trigger upon use, BUT because it is
a citation for a package -- it would not trigger unless explicitly tagged.
So we pretty much might like to add that tag withing dcite since it guarantees
that function gets called/citation must be in place (TODO: think more about it)

May be you see a better name for this tag @mvdoc ?

### CODE REVIEW

**Comment by mvdoc** [comment]
`always-cite` ?

**Comment by yarikoptic** [comment]
On Fri, 31 Jul 2015, Matteo Visconti di Oleggio Castello wrote:

>    always-cite ?

make sense... let me change ;)

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by yarikoptic** [comment]
github again didn't post my reply in time -- wouldn't people then assume that it would mean to cite it really always, ie used or not?   Actual "close to implementation" tag could be "cite-on-cite" but that would be confusing

**Comment by mvdoc** [comment]
I'm confused then: if this tag is used only for packages and modules, wouldn't it be more clean to have a function that users put at the beginning of the module or in `__init__.py` for the package that adds all 'persistent' references?

**Comment by yarikoptic** [comment]
On Fri, 31 Jul 2015, Matteo Visconti di Oleggio Castello wrote:

>    I'm confused then: if this tag is used only for packages and modules,
>    wouldn't it be more clean to have a function that users put at the
>    beginning of the module or in __init__.py for the package that adds all
>    'persistent' references?

that is the point, that not all of those should mean "cite me".
usually they shouldn't be cited merely if they got imported -- some
functionality should get used.  And that is the logic in the dump() now.
BUT for some of them it does make sense to cite them if they just got
imported, e.g. numpy, since if imported -- most probably they will get
used, and we don't want to decorate np.array ;)  Also this logic
"interferes" with me adding @dcite on methods e.g. in PyMVPA which will
use e.g. libsvm library.  So the path for that will be 'libsvm', so if
we decide on "cite-always" solely by path, it wouldn't get used.  I need
to mark it to be cited whenever that cite() gets executed (i.e. someone
did use SVM within PyMVPA).

That is why it is more 'cite-on-cite', i.e. "cite this module if cite()
for it was called"

hope this mumble clears it up ;)
-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by yarikoptic** [comment]
or we could flip it -- by default any call to 'cite' would mean what the citation needs to be listed, unless it gets a tag like "cite-if-children"?

**Comment by yarikoptic** [comment]
@mvdoc I have flipped the logic as we have discussed, although now I don't like it because by default now people would just not add it for their modules, leading to proliferation of citations...
may be I should drop this change and we then use "cite-module" (not "cite-on-use"). since we will use those terms (module/package) anyways...?  or "assume-used"? ;)

**Comment by mvdoc** [comment]
+1 for "cite-module" :-)

**Comment by yarikoptic** [comment]
@mvdoc  Done! -- if no other recommendations -- merge (whenever tests pass) ;)

**Comment by yarikoptic** [comment]
although now I don't like it again... this is the internal implementation detail, may be API then should better be adjusted . e.g. Citation would get an attribute "cite_module" which by default is False, and is not even relevant for non-package/module Citations.  But whenever it is necessary -- we allow to set it to True.  yeah -- that will be the way... let's keep "tags" to really provide groupping for them, and not mix-in "behavior"

**Comment by yarikoptic** [comment]
Let it be! and with this state I will tag a new release ;)

**Pull request merged**
