### PR TITLE
Improve/clean up packaging

### PR DESCRIPTION
**Pull request by jwodder**
See each commit message for explanations of the changes.

### CODE REVIEW

**Comment by yarikoptic** [comment]
I will drop python2 and resolve conflicts (via merge)

**Comment by jwodder** [comment]
@yarikoptic If you're dropping Python 2 support, you should also get rid of the `[bdist_wheel]universal` setting in `setup.cfg` and set `python_requires` in `setup.py`.

**Comment by yarikoptic** [comment]
thanks, done. Hopefully did it right ;-)

**Comment by yarikoptic** [comment]
ok, CI is green.  will not dive into coverage difference at this point.  Thank you @jwodder -- next step is a release to prepare for #178

**Pull request merged**
