### PR TITLE
Drop python 3.6 and 3.7 and pyupgrade to 3.8

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by a-detiste** [comment]
I don't see changes for Union & Optional.

I guess pyupgrade needs some parameter flag.

**Comment by yarikoptic** [comment]
https://github.com/asottile/pyupgrade#pep-604-typing-rewrites suggests that it is 3.10 feature

**Comment by a-detiste** [comment]
I read this as "either 3.10 or 3.8+using from __future__ import annotoations", but it's new information for me too.

**Comment by yarikoptic** [comment]
> I read this as "either 3.10 or 3.8+using from **future** import annotoations", but it's new information for me too.

might as well be, and just pyupgrade doesn't do such RFings automagically

**Pull request merged**
