### PR TITLE
RF to provide __main__ so we could do   python -m duecredit  existing script

### PR DESCRIPTION
**Pull request by yarikoptic**
This would avoid strict necessity to modify any script while in turn "enabling" duecredit and its injections.  To have it happen, since ```__main__.py``` gets imported after ```__init__.py``` I needed to make it possible to enable  `due`  after it was initially created.  That lead to somewhat "ugly" (or beautiful) DueSwitch.  Meanwhile I have moved majority of the supplemental code from `__init__.py` to `activate.py`.  Ideally it all needs unittests which I haven't tackled yet at least

### CODE REVIEW

**Comment by mvdoc** [comment]
OK. Will merge after unittests, as you teach me? :-P

**Comment by yarikoptic** [comment]
failed test "documented" in https://github.com/duecredit/duecredit/issues/40 now
otherwise, your desires were heard @mvdoc -- there are some tests. Check them out btw -- mocking all the way ;)

**Comment by yarikoptic** [comment]
Added few basic and smoke tests for cmdline -- we should beef up the coverage.  If interested -- look into TODO within test_cmdline for the summary -- a nice few lines exercise on mocking ;-)

**Comment by yarikoptic** [comment]
With @mvdoc blessing!

**Pull request merged**
