### PR TITLE
RF: _dump_collector_summary -> dump

### LINKED ISSUE #105: Make `DueSwitch._dump_collector_summary` public?
I am very new to this library, so there may be good reasons to avoid this. However, from my perspective, it seems natural to have `DueSwitch._dump_collector_summary` as a public function (perhaps exposed as `DueSwitch.due_summary` or something) to make using duecredit with standalone jupyter notebooks a little more self-contained. I am thinking along the lines of:

    # near top of notebook
    import os
    os.environ['DUECREDIT_ENABLE'] = 'yes'

    # body of notebook
    import fancymodule as fm
    fm.do_stuff()

    # section at the end
    fm.due._dump_collector_summary()

This way one doesn't have to deal with external files keeping track of citations, possibly being added to by other notebooks which could possibly be undesirable.

### PR DESCRIPTION
**Pull request by yarikoptic**
Closes #105 

Interface of the DueSwitch should avoid to grow to not collide with interface of collectors which it redefines to itself, but since `dump` is not available from those, we should be safe by just making `_dump_collector_summary` public

### CODE REVIEW

**Comment by yarikoptic** [comment]
failing tests... not sure what they are about... I think we actually fixed some of them in #103 so I might first attend to merging that big RF

**Comment by yarikoptic** [comment]
@mvdoc -- any deep thoughts for/against making `dump` public? ;)

**Comment by mvdoc** [comment]
no, I actually like the idea of using duecredit with IPython notebooks ;)

**Comment by yarikoptic** [comment]
ok -- tests pass, merging... yet to figure out coverage decrement

**Pull request merged**
