### PR TITLE
BF: change request command to make it work with zenodo too

### LINKED ISSUE #73: doi importer doesn't work with zenodo dois
see #72 

we should look into how http://www.doi2bib.org/ fetches bibtex entries, because it works for them. 

our way of getting bibtex entries returns Error 406 (not acceptable)

```
$ curl -LH "Accept: text/bibliography; style=bibtex" http://dx.doi.org/10.5281/zenodo.48147
<html><head><title>Apache Tomcat/7.0.26 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 406 - Not Acceptable</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Not Acceptable</u></p><p><b>description</b> <u>The resource identified by this request is only capable of generating responses with characteristics not acceptable according to the request "accept" headers (Not Acceptable).</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.26</h3></body></html>%
```

### PR DESCRIPTION
**Pull request by mvdoc**
It was actually easier than we thought. Kudos to @davidagraf and code in https://github.com/davidagraf/doi2bib/blob/master/app/doi2bib.js 

closes #73 and #72

### CODE REVIEW

**Comment by yarikoptic** [comment]
Ha.. Cool. I still think that eventually we should seek support of multiple providers here. But great that it works ATM with this minimal fix... I still wonder why though, especially since we have followed official specs iirc

NB I thought that appveyor setup worked at some point but now it seems to show that all builds failed... Strange

**Comment by yarikoptic** [comment]
ah, forgot that fixes to be done for appveyer setup which was never enabled really yet: https://github.com/duecredit/duecredit/pull/70

**Comment by alexsavio** [comment]
Hi,

Thanks for working on this! I have tested it on nipype's zenodo DOI. I put the following on the code (both references, the Zenodo DOI and the FNINF DOI:

```
due.cite(Doi("10.5281/zenodo.50186"),
         description="Zenodo: Nipype: a flexible, lightweight and extensible "
                     "neuroimaging data processing framework in Python",
          tags=["reference-implementation"],
          path='nipype')

due.cite(Doi("10.3389/fninf.2011.00013"),
         description="Nipype: a flexible, lightweight and extensible "
                     "neuroimaging data processing framework in Python",
         tags=["reference-implementation"],
         path='nipype')
```

Before this fix I wasn't getting any difference or message regarding the warning for the Zenodo DOI.
But I get now this error message:
```
DueCredit Report:
- Access a cacophony of neuro-imaging file formats / nibabel (v 2.0.2) [1]
- Nipype: a flexible, lightweight and extensible neuroimaging data processing framework in Python / nipype (v UNKNOWN) [2, 3]
- Scientific tools library / numpy (v 1.11) [4]
- Scientific tools library / scipy (v 0.17) [5]

4 packages cited
0 modules cited
0 functions cited

References
----------

[1] Url('http://nipy.org/nibabel', key='http://nipy.org/nibabel')
[2] 2016-05-04 10:21:56,128 [ERROR  ] Failed to process BibTeX file /tmp/alexandre/tmpz9hwm8k4.bib: 'data' (io.py:269)
160504-10:21:56,128 duecredit ERROR  :
	 Failed to process BibTeX file /tmp/alexandre/tmpz9hwm8k4.bib: 'data'
ERRORED: 'data'
[3] Gorgolewski, K. et al., 2011. Nipype: A Flexible, Lightweight and Extensible Neuroimaging Data Processing Framework in Python. Frontiers in Neuroinformatics, 5.
[4] Van Der Walt, S., Colbert, S.C. & Varoquaux, G., 2011. The NumPy array: a structure for efficient numerical computation. Computing in Science & Engineering, 13(2), pp.22–30.
[5] Jones, E. et al., 2001. SciPy: Open source scientific tools for Python.
```

**Comment by mvdoc** [comment]
hehe, zenodo opened a pandora's box. the problem is that they use `@data` as a bibtex entry type, which is not one of the valid bibtex entry types. so citeproc-py fails at parsing it because it doesn't know how to. at the moment there are no solutions.

I'll open an issue to think about what to do. thanks @alexsavio for the report!

**Pull request merged**
